---
version: '3.8'
services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: abhi
  apache:
    image: httpd
    ports:
      - 8989:80
    links:
      - mydb:jenkins
  php:
    image: php:7.2-apache
    links:
      - mydb:jenkins
      - apache:httpd

...
